Release 5.0.1 - See CHANGELOG

diff --git a/install/etc/cont-init.d/30-wordpress b/install/etc/cont-init.d/30-wordpress
--- a/install/etc/cont-init.d/30-wordpress
+++ b/install/etc/cont-init.d/30-wordpress
@@ -52,8 +52,8 @@ if [ -n "$SITE_PORT" ]; then
 fi
 
 ### Create Directory if doesn't exist
-mkdir -p /www/wordpress
-chown -R nginx:www-data /www/wordpress
+mkdir -p ${NGINX_WEBROOT}
+chown -R nginx:www-data ${NGINX_WEBROOT}
 
 ### Make sure that DB is accessible
 while true; do
@@ -61,71 +61,71 @@ while true; do
     out="`$mysqlcmd -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1`"
     echo "$out" | grep -E "COUNT|Enter" 2>&1 > /dev/null
     if [ $? -eq 0 ]; then
-        echo "** [wordpress] MariaDB Server '"$DB_HOST"' is available"
+        echo "** [wordpress] MariaDB Server '{$DB_HOST}' is available"
         break
     fi
-    echo "** [wordpress] MariaDB Server '"$DB_HOST"' unavailable. Sleeping a little bit ..."
+    echo "** [wordpress] MariaDB Server '${DB_HOST}' unavailable. Sleeping a little bit ..."
     sleep 5
 done
 
 ### Perform Nginx reverse proxy modifications
 if [ "$ENABLE_HTTPS_REVERSE_PROXY" = "TRUE" ] || [ "$ENABLE_HTTPS_REVERSE_PROXY" = "true" ]; then
-    sed -i -e "s/<REVERSE_PROXY>/on/g" /etc/nginx/conf.d/default.conf
+    echo "fastcgi_param  HTTPS 'on';" >> /etc/nginx/fastcgi_params
     PROTOCOL="https://"
 else
     echo "** [wordpress] Disabling Nginx Reverse Proxy HTTPS Termination Support"
-    sed -i -e "s/<REVERSE_PROXY>/off/g" /etc/nginx/conf.d/default.conf
+    echo "fastcgi_param  HTTPS 'off';" >> /etc/nginx/fastcgi_params
     PROTOCOL="http://"
 fi
 
 ### Check to see if this is a new install, if yes download Wordpress and other pieces...
-if [ ! -f /www/wordpress/wp-load.php ] ; then
+if [ ! -f ${NGINX_WEBROOT}/wp-load.php ] ; then
     if [ ! -n "$ADMIN_EMAIL" ]; then
-        echo '** [wordpress] ERROR: No Admin Email Address Entered!'
+        echo "** [wordpress] ERROR: No Admin Email Address Entered!""
         exit 1
     fi
 
     if [ ! -n "$ADMIN_PASS" ]; then
-        echo '** [wordpress] ERROR: No Admin Pass Entered!'
+        echo "** [wordpress] ERROR: No Admin Pass Entered!""
         exit 1
     fi
 
    echo "** [wordpress] Wordpress Installation not found, Downloading and setting up - Please wait 1-3 minutes"
-   cd /www/wordpress
+   cd ${NGINX_WEBROOT}
    silent sudo -u nginx wp-cli core download --locale=${SITE_LOCALE}
    silent sudo -u nginx wp-cli core config --dbhost=${DB_HOST} --dbname=${DB_NAME} --dbprefix=${DB_PREFIX} --dbuser=${DB_USER} --dbpass=${DB_PASS} --dbcharset=${DB_CHARSET}
    silent sudo -u nginx wp-cli core install --url=${PROTOCOL}${SITE_URL}${SITE_PORT} --title="${SITE_TITLE}" --admin_user=${ADMIN_USER} --admin_password=${ADMIN_PASS} --admin_email=${ADMIN_EMAIL} --skip-email
    chmod 644 wp-config.php
 ### Add URL information to allow for switching host/domainnames easily
-   echo "define( 'WP_HOME', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );" >> /www/wordpress/wp-config.php
-   echo "define( 'WP_SITEURL', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );" >> /www/wordpress/wp-config.php
-   silent rm -rf /www/wordpress/readme.html
-   silent rm -rf /www/wordpress/license.txt
-   silent rm -rf /www/wordpress/wp-content/plugins/hello.php
-   silent chown nginx:www-data /www/wordpress
+   echo "define( 'WP_HOME', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );" >> ${NGINX_WEBROOT}/wp-config.php
+   echo "define( 'WP_SITEURL', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );" >> ${NGINX_WEBROOT}/wp-config.php
+   silent rm -rf ${NGINX_WEBROOT}/readme.html
+   silent rm -rf ${NGINX_WEBROOT}/license.txt
+   silent rm -rf ${NGINX_WEBROOT}/wp-content/plugins/hello.php
+   silent chown nginx:www-data ${NGINX_WEBROOT}
 else
 
-   if ! grep -c -q "'WP_HOME'" /www/wordpress/wp-config.php ; then
-       echo "define( 'WP_HOME', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );" >> /www/wordpress/wp-config.php
+   if ! grep -c -q "'WP_HOME'" ${NGINX_WEBROOT}/wp-config.php ; then
+       echo "define( 'WP_HOME', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );" >> ${NGINX_WEBROOT}/wp-config.php
    fi
 
-   if ! grep -c -q "'WP_SITEURL'" /www/wordpress/wp-config.php ; then
-       echo "define( 'WP_SITEURL', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );" >> /www/wordpress/wp-config.php
+   if ! grep -c -q "'WP_SITEURL'" ${NGINX_WEBROOT}/wp-config.php ; then
+       echo "define( 'WP_SITEURL', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );" >> ${NGINX_WEBROOT}/wp-config.php
    fi
 
 ### Change URLs if different   
-   OLDURL=`grep "WP_HOME" /www/wordpress/wp-config.php | cut -d \' -f 4`
+   OLDURL=`grep "WP_HOME" ${NGINX_WEBROOT}/wp-config.php | cut -d \' -f 4`
    if [ "$OLDURL" != "${PROTOCOL}${SITE_URL}${SITE_PORT}" ]; then
-       cd /www/wordpress
+       cd ${NGINX_WEBROOT}
        echo "** [wordpress] Modifying wordpress to serve from ${OLDURL} to ${PROTOCOL}${SITE_URL}${SITE_PORT} - Please wait"
-       sed -i "s#define( 'WP_HOME'.*#define( 'WP_HOME', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );#g" /www/wordpress/wp-config.php
-       sed -i "s#define( 'WP_SITEURL'.*#define( 'WP_SITEURL', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );#g" /www/wordpress/wp-config.php
+       sed -i "s#define( 'WP_HOME'.*#define( 'WP_HOME', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );#g" ${NGINX_WEBROOT}/wp-config.php
+       sed -i "s#define( 'WP_SITEURL'.*#define( 'WP_SITEURL', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );#g" ${NGINX_WEBROOT}/wp-config.php
        silent sudo -u nginx wp-cli search-replace '${OLD_URL}' '${PROTOCOL}${SITE_URL}${SITE_PORT}' --skip-columns=guid
    fi 
 fi
 
 ### Force Reset Permissions for Security
-chown -R nginx:www-data /www/wordpress
+chown -R nginx:www-data ${NGINX_WEBROOT}
 echo "** [wordpress] Wordpress Initialization Complete, now starting webserver and PHP engine"
 
 touch /tmp/state/30-init-wordpress
